run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 3
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/tyrads-com/tyrads-go-sdk-iframe
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - lll
    - goconst
    - gocritic
    - revive
    - gosec

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - lll
  exclude:
    # Exclude known linter issues
    - "Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked"
  max-issues-per-linter: 0
  max-same-issues: 0